import 'server-only';

// Generated by scripts/generate-payd-allowlist.mjs from backend/internal/api/openapi.yaml.
// Do not edit by hand; run `node scripts/generate-payd-allowlist.mjs`.
export type PaydRoute = { readonly method: string; readonly path: string; readonly public?: boolean };

export const paydRoutes: readonly PaydRoute[] = [
  {
    "method": "GET",
    "path": "chain/status"
  },
  {
    "method": "GET",
    "path": "chain/quota"
  },
  {
    "method": "GET",
    "path": "workers"
  },
  {
    "method": "GET",
    "path": "audit"
  },
  {
    "method": "GET",
    "path": "resources/grants"
  },
  {
    "method": "GET",
    "path": "resources/wallet"
  },
  {
    "method": "GET",
    "path": "config"
  },
  {
    "method": "GET",
    "path": "reports/volume"
  },
  {
    "method": "GET",
    "path": "reports/fees"
  },
  {
    "method": "GET",
    "path": "export/orders.csv"
  },
  {
    "method": "GET",
    "path": "export/withdrawals.csv"
  },
  {
    "method": "GET",
    "path": "payments"
  },
  {
    "method": "POST",
    "path": "orders/{id}/extend"
  },
  {
    "method": "GET",
    "path": "orders/{id}/events"
  },
  {
    "method": "POST",
    "path": "withdrawals/{id}/resolve"
  },
  {
    "method": "POST",
    "path": "withdrawals/estimate"
  },
  {
    "method": "GET",
    "path": "auth/whoami"
  },
  {
    "method": "GET",
    "path": "assets"
  },
  {
    "method": "POST",
    "path": "ipn/test"
  },
  {
    "method": "POST",
    "path": "ipn/replay"
  },
  {
    "method": "POST",
    "path": "orders"
  },
  {
    "method": "GET",
    "path": "orders"
  },
  {
    "method": "GET",
    "path": "orders/funded-terminal"
  },
  {
    "method": "GET",
    "path": "orders/{id}"
  },
  {
    "method": "POST",
    "path": "orders/{id}/cancel"
  },
  {
    "method": "POST",
    "path": "orders/{id}/resolve"
  },
  {
    "method": "GET",
    "path": "payments/unattributed"
  },
  {
    "method": "GET",
    "path": "payments/orphaned"
  },
  {
    "method": "POST",
    "path": "payments/{id}/attribute"
  },
  {
    "method": "GET",
    "path": "wallets"
  },
  {
    "method": "GET",
    "path": "wallets/with-balance"
  },
  {
    "method": "GET",
    "path": "wallets/{address}"
  },
  {
    "method": "POST",
    "path": "wallets/{address}/disable"
  },
  {
    "method": "POST",
    "path": "wallets/{address}/delegate"
  },
  {
    "method": "GET",
    "path": "ipn/dead"
  },
  {
    "method": "POST",
    "path": "ipn/{id}/retry"
  },
  {
    "method": "GET",
    "path": "ipn/consumers"
  },
  {
    "method": "GET",
    "path": "chain/params"
  },
  {
    "method": "GET",
    "path": "prices"
  },
  {
    "method": "GET",
    "path": "stats"
  },
  {
    "method": "GET",
    "path": "energy/status"
  },
  {
    "method": "GET",
    "path": "energy/purchases"
  },
  {
    "method": "GET",
    "path": "wallets/needs-resources"
  },
  {
    "method": "POST",
    "path": "wallets/{address}/clear-drift"
  },
  {
    "method": "POST",
    "path": "withdrawals"
  },
  {
    "method": "GET",
    "path": "withdrawals"
  },
  {
    "method": "GET",
    "path": "withdrawals/limits"
  },
  {
    "method": "GET",
    "path": "withdrawals/{id}"
  },
  {
    "method": "GET",
    "path": "healthz",
    "public": true
  },
  {
    "method": "GET",
    "path": "readyz",
    "public": true
  },
  {
    "method": "GET",
    "path": "openapi.yaml",
    "public": true
  }
] as const;

export function findAllowedRoute(method: string, path: string[]): PaydRoute | undefined {
  return paydRoutes.find((route) => {
    const parts = route.path.split('/');
    if (route.method !== method || parts.length !== path.length) return false;
    return parts.every((part, index) => part.startsWith('{') && part.endsWith('}') ? path[index] !== '' : part === path[index]);
  });
}

export function matchAllowedRoute(method: string, path: string[]): boolean {
  return findAllowedRoute(method, path) !== undefined;
}

// Public payd routes are served at the root, not under /api/v1, and take no key.
export function upstreamPath(route: PaydRoute, path: string[]): string {
  const joined = path.map(encodeURIComponent).join('/');
  return route.public ? `/${joined}` : `/api/v1/${joined}`;
}
